apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "common.entity.name" . }}
spec:
  hostnames:
  {{- range .Values.exposure.hostnames }}
    - {{ . | quote }}
  {{- end }}
  parentRefs:
{{ toYaml .Values.gatewayApi.httpRoute.parentRefs | nindent 4 }}
  rules:
    - backendRefs:
        - name: {{ include "common.entity.name" . }}
          namespace: {{ .Release.Namespace }}
          port: {{ .Values.port }}
      {{- if or .Values.gatewayApi.httpRoute.filters .Values.traefik.enabled }}
      filters:
      {{- with .Values.gatewayApi.httpRoute.filters }}
        {{ toYaml . | nindent 6 }}
      {{- end }}
      {{- if .Values.traefik.enabled }}
        {{ toYaml .Values.gatewayApi.httpRoute.corsFilters | nindent 6 }}
      {{- end }}
      {{- end }}
      matches:
        - path:
            type: PathPrefix
            value: {{ .Values.gatewayApi.httpRoute.pathPrefix }}