kind: Service
apiVersion: v1
metadata:
  name: {{ include "common.entity.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    dxp.sap.com/metrics: enabled
spec:
  selector:
    app: {{ include "common.entity.name" . }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.port }}
  type: ClusterIP
