apiVersion: v2
name: platform-mesh-operator
description: A Helm chart to automate bootstrapping of new environment
type: application
version: 0.18.1
appVersion: "v0.44.2"
dependencies:
  - name: common
    version: 0.11.2
    repository: oci://ghcr.io/platform-mesh/helm-charts
  - name: platform-mesh-operator-crds
    version: 0.3.1
    repository: oci://ghcr.io/platform-mesh/helm-charts
    condition: crds.enabled
