apiVersion: v2
name: platform-mesh-operator
description: A Helm chart to automate bootstrapping of new environment
type: application
version: 0.16.23
appVersion: "v0.34.6"
dependencies:
  - name: common
    version: 0.10.0
    repository: oci://ghcr.io/platform-mesh/helm-charts
  - name: platform-mesh-operator-crds
    version: 0.3.1
    repository: oci://ghcr.io/platform-mesh/helm-charts
    condition: crds.enabled
