apiVersion: v2
name: platform-mesh-operator
description: A Helm chart to automate bootstrapping of new environment
type: application
version: 0.7.1
appVersion: "v0.19.6"
dependencies:
  - name: common
    version: 0.7.0
    repository: oci://ghcr.io/platform-mesh/helm-charts
  - name: platform-mesh-operator-crds
    version: 0.2.2
    repository: oci://ghcr.io/platform-mesh/helm-charts
    condition: components.crds.enabled
