crds:
  enabled: true

deployment:
  replicas: 1

log:
  level: debug

operator:
  leaderElect: true

image:
  name: ghcr.io/platform-mesh/platform-mesh-operator

tracing:
  enabled: false
  collector:
    endpoint: observability-opentelemetry-collector.observability.svc.cluster.local:4317

extraArgs:
  - --subroutines-feature-toggles-enabled=true

istio:
  enabled: false

kubeConfigPlatformMesh:
  # -- Enables reconciliation of PlatformMesh resources on remote clusters
  enabled: false
  # -- Name of the secret containing the kubeconfig for remote cluster access where the PlatformMesh resources will be deployed
  secretName: "platform-mesh-kubeconfig"

kubeConfigDeployment:
  # -- Enables deployment to remote clusters. Set to true if the operator is not deployed on the same cluster where the FluxCD artefacts will be created.
  enabled: false
  # -- Name of the secret containing the kubeconfig for the cluster where the created FluxCD artefacts will be created. NOTE: target deployment will alway be same as the cluster where the Platform Mesh resource lives.
  secretName: "platform-mesh-infra-kubeconfig"
