crds:
  enabled: true

deployment:
  replicas: 1

log:
  level: debug

operator:
  leaderElect: true

image:
  name: ghcr.io/platform-mesh/platform-mesh-operator

tracing:
  enabled: false
  collector:
    endpoint: observability-opentelemetry-collector.observability.svc.cluster.local:4317

extraArgs:
  - --subroutines-feature-toggles-enabled=true

istio:
  enabled: false

kubeConfig:
  # -- Allows the mounting of an external kubeconfig. If the kubeconfig is set, it is expected that the service account, that is used, is not connected to this chart and the rbac resources will not be generated.
  enabled: false
  secretName: "platform-mesh-kubeconfig"
