{{- if eq (include "common.istioEnabled" .) "true" -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "common.entity.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  gateways:
  - {{ .Release.Namespace }}/gateway
  hosts:
    {{- .Values.istio.virtualService.hosts | toYaml | nindent 2}}
  http:
  - {{- .Values.istio.virtualService.matcher | toYaml | nindent 4}}
    route:
    - destination:
        host: {{ include "common.entity.name" . }}.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: 8080
{{- end -}}