type: application
apiVersion: v2
name: infra
description: A Helm chart for Kubernetes
version: 0.20.2
appVersion: "0.0.0"

dependencies:
  - name: common
    version: 0.11.1
    repository: oci://ghcr.io/platform-mesh/helm-charts
