apiVersion: v1
kind: ConfigMap
metadata:
  name: ocmconfig
  namespace: default
data:
  .ocmconfig: |
    type: generic.config.ocm.software/v1
    configurations:
      - type: credentials.config.ocm.software
        consumers: []
