apiVersion: v1
kind: ConfigMap
metadata:
  name: ocmconfig
  namespace: default
data:
  .ocmconfig: |
    type: generic.config.ocm.software/v1
    configurations:
      - type: ocm.config.ocm.software
        resolvers:
          - repository:
              type: OCIRegistry
              baseUrl: https://ghcr.io/platform-mesh
            prefix: github.com/platform-mesh
          - repository:
              type: OCIRegistry
              baseUrl: https://ghcr.io/platform-mesh
            prefix: github.com/crossplane
          - repository:
              type: OCIRegistry
              baseUrl: https://ghcr.io/platform-mesh
            prefix: github.com/kcp-dev
          - repository:
              type: OCIRegistry
              baseUrl: https://ghcr.io/platform-mesh
            prefix: github.com/openfga
          - repository:
              type: OCIRegistry
              baseUrl: https://ghcr.io/platform-mesh
            prefix: github.com/kubernetes-sigs
          - repository:
              type: OCIRegistry
              baseUrl: https://ghcr.io/platform-mesh
            prefix: github.com/traefik/traefik
          - repository:
              type: OCIRegistry
              baseUrl: https://ghcr.io/platform-mesh
            prefix: github.com/cert-manager
          - repository:
            type: OCIRegistry
            baseUrl: https://europe-docker.pkg.dev/gardener-project/releases
            prefix: github.com/gardener
