apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.entity.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  revisionHistoryLimit: {{ .Values.deployment.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "common.labelMatcher" . | indent 6 }}
  template:
    metadata:
      labels:
        {{- include "common.labelMatcher" . | indent 8 }}
        control-plane: controller-manager
    spec:
      {{- include "common.imagePullSecret" . | indent 6 }}
      {{- include "common.pod.securityContext" . | indent 6 }}
      terminationGracePeriodSeconds: {{ include "common.terminationGracePeriodSeconds" .}}
      serviceAccountName: {{ include "common.entity.name" . }}
      containers:
      - {{- include "common.podBasics" . | indent 8 }}
        {{- include "common.container.securityContext" . | indent 8 }}
        {{- include "common.operatorHealthAndReadyness" . | indent 8}}
        ports:
        {{- include "common.PortsMetricsHealth" . | nindent 10 }}
        args:
          {{- include "common.commonOperatorArgs" . | indent 8 }}
        env:
        {{- include "common.basicEnvironment" . | nindent 10 }}
          {{- if .Values.kubeconfigSecret }}
          - name: KCP_KUBECONFIG
            value: /api-kubeconfig/kubeconfig
          {{- end }}
          - name: OPENSEARCH_URL
            value: {{ .Values.opensearch.url }}
          {{- if .Values.opensearch.username }}
          - name: OPENSEARCH_USERNAME
            value: {{ .Values.opensearch.username }}
          {{- end }}
          {{- if .Values.opensearch.passwordSecretName }}
          - name: OPENSEARCH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.opensearch.passwordSecretName }}
                key: {{ .Values.opensearch.passwordSecretKey }}
          {{- end }}
        volumeMounts:
          {{- if .Values.kubeconfigSecret }}
          - name: external-api-server
            mountPath: /api-kubeconfig
          {{- end }}
          {{- include "common.extraVolumeMounts" . | nindent 10 }}
      volumes:
        {{- if .Values.kubeconfigSecret }}
        - name: external-api-server
          secret:
            secretName: {{ .Values.kubeconfigSecret }}
        {{- end }}
        {{- include "common.extraVolumes" . | nindent 8 }}
