{{- $config := .Values.etcdDruid -}}
{{- $service := "etcd-druid" -}}
{{- if $config.enabled -}}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ $service}}
  namespace: {{ $.Release.Namespace }}
spec:
  {{- if $config.helmRepo }}
  chart:
    spec:
      chart: {{ $config.chart | default $service }}
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: {{ $service }}
  {{- end }}
  {{- if $config.gitRepo }}
  chart:
    spec:
      chart: {{ $config.path | default $service }}
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: {{ $service }}
  {{- end }}
  {{- if not (or $config.helmRepo $config.gitRepo) }}
  chartRef:
    kind: OCIRepository
    name: {{ $service }}
    namespace: {{ $.Release.Namespace }}
  {{- end }}
  interval: 1m
  releaseName: {{ $service}}
  targetNamespace: {{ $config.targetNamespace }}
  dependsOn:
    {{ $config.dependsOn | toYaml | nindent 4 }}
  timeout: 15m
  values:
{{ tpl (toYaml $config.values) $ | indent 4 }}
---
{{ end -}}
