{{- if .Values.etcdDruid.enabled }}
apiVersion: delivery.ocm.software/v1alpha1
kind: Resource
metadata:
  annotations:
    artifact: image
    repo: oci
    for: {{ .Values.etcdDruid.name }}
    path: image.tag
  name: {{ .Values.etcdDruid.name }}-image
spec:
  componentRef:
    name: {{ .Values.ocm.component.name }}
  interval: {{ .Values.ocm.interval }}
  ocmConfig:
    - apiVersion: delivery.ocm.software/v1alpha1
      kind: Repository
      name: {{ .Values.etcdDruid.ocm.repo.name }}
      namespace: {{ .Release.Namespace }}
  resource:
    byReference:
      referencePath:
      {{- range .Values.ocm.referencePath }}
        - name: {{ . }}
      {{- end }}
        - name: {{   .Values.etcdDruid.name }}
      resource:
        name: {{ .Values.etcdDruid.ocmImageResourceName }}
  skipVerify: {{ .Values.ocm.skipVerify }}
{{- end }}