apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "common.entity.name" . }}
  namespace: {{ .Values.terminal.namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "common.entity.name" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "common.entity.name" . }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "common.entity.name" . }}-leader-election
subjects:
- kind: ServiceAccount
  name: {{ include "common.entity.name" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "common.entity.name" . }}-leader-election
  apiGroup: rbac.authorization.k8s.io