apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../components/platform-mesh-operator-resource
  - ../../components/ocm
patches:
  - target:
      kind: Component
      name: platform-mesh
    patch: |
      - op: add
        path: /metadata/namespace
        value: platform-mesh-system
      - op: replace
        path: /spec/ocmConfig/0/namespace
        value: platform-mesh-system
  - target:
      kind: Repository
      name: platform-mesh
    patch: |
      - op: add
        path: /metadata/namespace
        value: platform-mesh-system
