apiVersion: v2
name: iam-service
description: A Helm chart for Kubernetes
appVersion: v0.12.13
version: 0.12.28
dependencies:
  - name: common
    version: 0.10.0
    repository: oci://ghcr.io/platform-mesh/helm-charts
