apiVersion: v2
name: iam-service
description: A Helm chart for Kubernetes
appVersion: v0.12.36
version: 0.14.13
dependencies:
  - name: common
    version: 0.11.1
    repository: oci://ghcr.io/platform-mesh/helm-charts
