apiVersion: v2
name: iam-service
description: A Helm chart for Kubernetes
appVersion: v0.12.28
version: 0.14.4
dependencies:
  - name: common
    version: 0.11.0
    repository: oci://ghcr.io/platform-mesh/helm-charts
