apiVersion: v2
name: iam-service
description: A Helm chart for Kubernetes
appVersion: v0.11.30
version: 0.11.36
dependencies:
  - name: common
    version: 0.10.0
    repository: oci://ghcr.io/platform-mesh/helm-charts
