apiVersion: v2
name: iam-service
description: A Helm chart for Kubernetes
appVersion: v0.12.34
version: 0.14.12
dependencies:
  - name: common
    version: 0.11.1
    repository: oci://ghcr.io/platform-mesh/helm-charts
