apiVersion: v2
name: iam-service
description: A Helm chart for Kubernetes
version: 0.15.4
appVersion: v0.12.45
dependencies:
  - name: common
    version: 0.11.2
    repository: oci://ghcr.io/platform-mesh/helm-charts
