apiVersion: v2
name: security-operator
description: A Helm chart for security-operator
type: application
version: 0.18.37
appVersion: "v0.9.36"
dependencies:
  - name: security-operator-crds
    version: 0.3.0
    condition: crds.enabled
    repository: oci://ghcr.io/platform-mesh/helm-charts
  - name: common
    version: 0.7.0
    repository: oci://ghcr.io/platform-mesh/helm-charts
