apiVersion: v2
name: security-operator
description: A Helm chart for security-operator
type: application
version: 0.19.30
appVersion: "v0.11.0"
dependencies:
  - name: security-operator-crds
    version: 0.3.0
    condition: crds.enabled
    repository: oci://ghcr.io/platform-mesh/helm-charts
  - name: common
    version: 0.10.0
    repository: oci://ghcr.io/platform-mesh/helm-charts
