apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.entity.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  revisionHistoryLimit: {{ .Values.deployment.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "common.labelMatcher" . | indent 6 }}
  template:
    metadata:
      labels:
        {{- include "common.labelMatcher" . | indent 8 }}
        control-plane: controller-manager
    spec:
      {{- include "common.imagePullSecret" . | indent 6 }}
      {{- include "common.pod.securityContext" . | indent 6 }}
      terminationGracePeriodSeconds: {{ include "common.terminationGracePeriodSeconds" .}}
      containers:
      - {{- include "common.podBasics" . | indent 8 }}
        {{- include "common.container.securityContext" . | indent 8 }}
        {{- include "common.operatorHealthAndReadyness" . | indent 8}}
        ports:
        {{- include "common.PortsMetricsHealth" . | nindent 10 }}
        args:
          - fga
          {{- with .Values.keycloakSecret }}
          - --invite-keycloak-password-file=/keycloak-credentials/secret
          {{- end }}
          {{- with .Values.fga.inviteKeycloakBaseUrl }}
          - --invite-keycloak-base-url={{ . }}
          {{- end }}
          {{- with .Values.baseDomain }}
          - --base-domain={{ . }}
          {{- end }}
          {{- with .Values.fga.extraArgs }}
          {{ toYaml . | nindent 10}}
          {{- end }}
          {{- include "common.commonOperatorArgs" . | indent 8 }}
        env:
        {{- include "common.basicEnvironment" . | nindent 10 }}
          - name: FGA_TARGET
            value: {{ .Values.fga.target }}
          {{- if .Values.kubeconfigSecret }}
          - name: KCP_KUBECONFIG
            value: /api-kubeconfig/kubeconfig
          {{- end }}
          - name: INVITE_KEYCLOAK_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ .Values.keycloak.client.secret.name }}
                key: {{ .Values.keycloak.client.secret.key }}
        volumeMounts:
          {{- if .Values.kubeconfigSecret }}
          - name: external-api-server
            mountPath: /api-kubeconfig
          {{- end }}
          {{- if .Values.keycloakSecret }}
          - name: keycloak-credentials
            mountPath: /keycloak-credentials
            readOnly: true
          {{- end }}
          {{- if .Values.caSecret }}
          - name: domain-ca
            mountPath: /etc/ssl/certs/domain-ca.crt
            subPath: tls.crt
            readOnly: true
          {{- end }}
          {{- include "common.extraVolumeMounts" . | nindent 10 }}
      volumes:
        {{- if .Values.kubeconfigSecret }}
        - name: external-api-server
          secret:
            secretName: {{ .Values.kubeconfigSecret }}
        {{- end }}
        {{- if .Values.keycloakSecret }}
        - name: keycloak-credentials
          secret:
            secretName: {{ .Values.keycloakSecret }}
        {{- end }}
        {{- if .Values.caSecret }}
        - name: domain-ca
          secret:
            secretName: {{ .Values.caSecret }}
        {{- end }}
        {{- include "common.extraVolumes" . | nindent 8 }}
      {{- if .Values.hostAliases.enabled }}
      hostAliases:
        {{- with .Values.hostAliases.items }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
