{{- if .Values.certManager.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ .Values.certManager.name }}
spec:
  chartRef:
    kind: OCIRepository
    name: {{ .Values.certManager.name }}
    namespace: default
  interval: {{ .Values.certManager.interval }}
  releaseName: {{ .Values.certManager.name }}
  targetNamespace: {{ .Values.certManager.targetNamespace }}
  timeout: {{ .Values.timeout }}
  values:
    {{- toYaml .Values.certManager.values | nindent 4 }}
  {{- if .Values.fluxCD.kubeConfig.enabled }}
  kubeConfig:
    secretRef:
      name: {{ .Values.fluxCD.kubeConfig.secretRef.name }}
  {{- end }}
{{- end }}