apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ .Values.certManager.name }}
spec:
  chart:
    spec:
      chart: {{ .Values.certManager.name }}
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: {{ .Values.certManager.name }}
  interval: {{ .Values.certManager.interval }}
  releaseName: {{ .Values.certManager.name }}
  targetNamespace: {{ .Values.certManager.targetNamespace }}
  timeout: 15m
  values:
    {{- toYaml .Values.certManager.values | nindent 4 }}