apiVersion: v2
name: terminal-controller-manager
description: A Helm chart to deploy platform-mesh Terminal Controller Manager
type: application
version: 0.2.0
appVersion: "v0.2.0"
dependencies:
  - name: common
    version: 0.11.2
    repository: oci://ghcr.io/platform-mesh/helm-charts
