apiVersion: v2
name: extension-manager-operator
description: A Helm chart for extension-manager-operator which manages resources like ContentConfigurations and exposes REST `/validate` endpoint
type: application
version: 0.32.51
appVersion: "v0.4.27"
dependencies:
  - name: extension-manager-operator-crds
    version: 0.2.1
    condition: crds.enabled
    repository: oci://ghcr.io/platform-mesh/helm-charts
  - name: common
    version: 0.10.0
    repository: oci://ghcr.io/platform-mesh/helm-charts
