apiVersion: v2
name: extension-manager-operator
description: A Helm chart for extension-manager-operator which manages resources like ContentConfigurations and exposes REST `/validate` endpoint
type: application
version: 0.33.31
appVersion: "v0.4.97"
dependencies:
  - name: extension-manager-operator-crds
    version: 0.3.1
    condition: crds.enabled
    repository: oci://ghcr.io/platform-mesh/helm-charts
  - name: common
    version: 0.11.1
    repository: oci://ghcr.io/platform-mesh/helm-charts
