apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - apiexport-infra.provider.example.com.yaml
  - contentconfiguration.yaml
  - providermetadata.yaml
  - apiresourceschema-loadbalancers.infra.provider.example.com.yaml
  - apiresourceschema-securitygroups.infra.provider.example.com.yaml
  - apiresourceschema-sshkeypairs.infra.provider.example.com.yaml
  - apiresourceschema-subnets.infra.provider.example.com.yaml
  - apiresourceschema-virtualmachines.infra.provider.example.com.yaml
  - apiresourceschema-volumes.infra.provider.example.com.yaml
  - apiresourceschema-vpcs.infra.provider.example.com.yaml
  - apiresourceschema-clusters.infra.provider.example.com.yaml
  - rbac.yaml
