{{- if .Values.gatewayApi.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "common.entity.name" . }}
spec:
  {{- with .Values.gatewayApi.httpRoute.hostnames }}
  hostnames:
  {{- range . }}
  - {{ . | quote }}
  {{- end }}
  {{- end }}
  parentRefs:
{{ toYaml .Values.gatewayApi.httpRoute.parentRefs | nindent 4 }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: {{ .Values.gatewayApi.httpRoute.pathPrefix }}
    {{- if or .Values.gatewayApi.httpRoute.filters .Values.traefik.enabled }}
    filters:
    {{- with .Values.gatewayApi.httpRoute.filters }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.traefik.enabled }}
    {{ toYaml .Values.gatewayApi.httpRoute.corsFilters | nindent 4 }}
    {{- end }}
    {{- end }}
    backendRefs:
    - group: ""
      kind: Service
      name: {{ include "common.entity.name" . }}
      namespace: {{ .Release.Namespace }}
      port: 8080
{{- end }}