{{- if and .Values.webhooks.enabled .Values.webhooks.register -}}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "common.entity.name" . }}-validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "common.entity.name" . }}-serving-cert
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "common.entity.name" . }}-webhook
      namespace: {{ .Release.Namespace }}
      path: "/validate-core-platform-mesh-io-v1alpha1-identityproviderconfiguration"
      port: {{ .Values.webhooks.port }}
  failurePolicy: Fail
  name: vidp.kb.io
  rules:
  - apiGroups:
    - core.platform-mesh.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - identityproviderconfigurations
  sideEffects: None
{{- end -}}
