apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: keycloak
spec:
  {{- with .Values.keycloak.gatewayApi.hostnames }} 
  hostnames:
  {{- range . }}
  - {{ . | quote }}
  {{- end }}
  {{- end }}
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: {{ .Values.gatewayApi.name }}
    sectionName: {{ .Values.gatewayApi.main.gateway.name }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: {{ .Values.keycloak.gatewayApi.pathPrefix }}
    {{- with .Values.keycloak.gatewayApi.filters }}
    filters:
      {{ toYaml .Values.keycloak.gatewayApi.filters | nindent 6 }}
    {{- end }}
    backendRefs:
    - group: ""
      kind: Service
      name: {{ .Values.keycloak.service.name }}
      namespace: {{ .Release.Namespace }}
      port: {{ .Values.keycloak.service.port }}
