{{ if not .Values.kubeConfig.enabled }}
{{ if not .Values.kcp.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "common.entity.name" . }}
  namespace: {{ .Release.Namespace }}
rules:
  # gateway
  {{ if .Values.gateway.shouldImpersonate }}
  - apiGroups: [ "" ]
    resources: [ "users", "serviceaccounts" ]
    verbs: [ "impersonate" ]
  # old default permissions:
  - apiGroups: [ "*" ]
    resources: [ "*" ]
    verbs: [ "*" ]
  {{ end }}

  # listener
  # I know that for gateway we are giving much wider permissions, but let's preserve the needed permissions for listener
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
      - watch
  {{- if .Values.crds.enabled }}
  - apiGroups:
      - gateway.platform-mesh.io
    resources:
      - clusteraccesses
      - clusteraccesses/status
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  {{- end }}
  {{- if and .Values.rbac.createServiceAccountRules (not .Values.rbac.serviceAccounts) }}
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - serviceaccounts/token
    verbs:
      - create
  {{- end }}
{{ end }}
{{ end }}

