{{- if .Values.gatewayApi.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "common.entity.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- with .Values.gatewayApi.httpRoute.hostnames }}
  hostnames:
  {{- range . }}
  - {{ . | quote }}
  {{- end }}
  {{- end }}
  parentRefs:
{{ toYaml .Values.gatewayApi.httpRoute.parentRefs | nindent 4 }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: {{ .Values.gatewayApi.httpRoute.pathPrefix }}
    filters:
    {{ toYaml .Values.gatewayApi.httpRoute.filters | nindent 6 }}
    {{- if .Values.cors.enabled }}
    {{- toYaml .Values.gatewayApi.httpRoute.corsFilters | nindent 6 }}
    {{- end }}
    backendRefs:
    - name: {{ include "common.entity.name" . }}
      namespace: {{ .Release.Namespace }}
      port: 8080
{{- end }}
