{{- if not .Values.kubeConfig.enabled }}
{{- if not .Values.kcp.enabled }}
{{- if and .Values.rbac.createServiceAccountRules .Values.rbac.serviceAccounts }}
{{- $root := . }}
{{- $namespaces := dict }}
{{- range .Values.rbac.serviceAccounts }}
{{- $_ := set $namespaces .namespace (append (get $namespaces .namespace | default list) .name) }}
{{- end }}
{{- range $namespace, $names := $namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "common.entity.name" $root }}-sa-access
  namespace: {{ $namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "common.entity.name" $root }}-sa-access
subjects:
  - kind: ServiceAccount
    name: {{ include "common.entity.name" $root }}
    namespace: {{ $root.Release.Namespace }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
