apiVersion: v2
name: virtual-workspaces
description: A Helm chart to deploy platform-mesh virtual-workspaces
type: application
version: 0.2.9
appVersion: "v0.8.0"
dependencies:
  - name: common
    version: 0.9.0
    repository: oci://ghcr.io/platform-mesh/helm-charts
