apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - apiexport-core.platform-mesh.io.yaml
  - apiresourceschema-terminals.terminal.platform-mesh.io.yaml
  - contentconfiguration-getting-started.yaml
  - contentconfiguration-main-home.yaml
  - contentconfiguration-main-iam-ui.yaml
  - contentconfiguration-main-accounts.yaml
  - contentconfiguration-account-home.yaml
  - contentconfiguration-account-accounts.yaml
  - contentconfiguration-account-iam-ui.yaml
  - contentconfiguration-account-workspace-dashboard.yaml
  - contentconfiguration-account-platform-mesh.yaml
  - contentconfiguration-account-kcp.yaml
  - contentconfiguration-account-kubernetes.yaml
