apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry]
      config_path = "/etc/containerd/certs.d"
nodes:
- role: control-plane
  extraMounts:
  - hostPath: ./containerd-certs.d
    containerPath: /etc/containerd/certs.d
    readOnly: true
  extraPortMappings:
  - containerPort: 31000
    hostPort: 8443
    protocol: TCP
    listenAddress: "127.0.0.1"
  - containerPort: 32000
    hostPort: 15021
    protocol: TCP
    listenAddress: "127.0.0.1"
