{{ $values := .Values }}
{{- range $service, $config := .Values.services }}
{{- if and $config.enabled (not $config.skipHelmRelease) -}}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ $service}}
  namespace: {{ $.Release.Namespace }}
spec:
  {{- if $config.helmRepo }}
  chart:
    spec:
      chart: {{ $config.chart | default $service }}
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: {{ $service }}
  {{- end }}
  {{- if $config.gitRepo }}
  chart:
    spec:
      chart: {{ $config.path | default $service }}
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: {{ $service }}
  {{- end }}
  {{- if not (or $config.helmRepo $config.gitRepo) }}
  chartRef:
    kind: OCIRepository
    name: {{ $service }}
    namespace: {{ $.Release.Namespace }}
  {{- end }}
  interval: 1m
  releaseName: {{ $service}}
  targetNamespace: {{ $config.targetNamespace | default $values.targetNamespace }}
  dependsOn:
    {{ $config.dependsOn | toYaml | nindent 4 }}
  timeout: 15m
  values:
    {{- $finalValues := (default dict $config.values) | deepCopy -}}
    {{- $_ := include "hostaliases.injectGlobalHostAliases" (dict "dict" $finalValues "root" $) -}}
    {{- tpl ( toYaml $finalValues ) $ | nindent 4 }}
---
{{ end -}}
{{ end -}}
