apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - apiexport-monitoring.provider.example.com.yaml
  - apiresourceschema-prometheusinstances.monitoring.provider.example.com.yaml
  - providermetadata.yaml
  - contentconfiguration.yaml
  - rbac.yaml