apiVersion: ui.platform-mesh.io/v1alpha1
kind: ProviderMetadata
metadata:
  name: monitoring.provider.example.com
spec:
  displayName: Example Monitoring Provider
  description: |
    This provider offers monitoring capabilities for Kubernetes clusters.
  contacts:
  - displayName: Maria Garcia
    email: maria.garcia@abc.com
    role: ["Technical Support Lead"]
  preferredSupportChannels:
  - displayName: Monitoring Help Desk
  icon:
    light:
      url: https://landscape.cncf.io/logos/4d6a2b87a6c9a01ed1b82cef5db978e273adb99fda44d47e5dae48f75207147c.svg
    dark:
      url: https://landscape.cncf.io/logos/4d6a2b87a6c9a01ed1b82cef5db978e273adb99fda44d47e5dae48f75207147c.svg

