apiVersion: v2
name: account-operator
description: A Helm chart to deploy platform-mesh Account-Operator
type: application
version: 0.15.15
appVersion: "v0.11.14"
dependencies:
  - name: account-operator-crds
    version: 0.2.5
    condition: crds.enabled
    repository: oci://ghcr.io/platform-mesh/helm-charts
  - name: common
    version: 0.11.2
    repository: oci://ghcr.io/platform-mesh/helm-charts
