timeout: 30m
ocm:
  skipVerify: true
  interval: 3m
  referencePath: []
  component:
    name: platform-mesh
  repo:
    name: platform-mesh

gatewayApi:
  enabled: true
  name: gateway-api
  ocmResourceName: crds

  kustomization:
    interval: 1m
    path: ./config/crd/experimental
    install:
      crds: Skip

traefik:
  enabled: true
  targetNamespace: default
  name: traefik
  ocmResourceName: chart
  interval: 1m
  chart:
    name: traefik
  values:
    experimental:
      kubernetesGateway:
        enabled: true
    providers:
      kubernetesGateway:
        enabled: true
        experimentalChannel: true
    gatewayClass:
      enabled: true
    service:
      type: NodePort
      spec:
        clusterIP: 10.96.188.4
    ports:
      websecure:
        nodePort: 31000
        exposedPort: 8443
    gateway:
      enabled: false

traefikCRDs:
  enabled: true
  targetNamespace: default
  name: traefik-crds
  ocmComponentName: traefik
  ocmResourceName: crds
  interval: 1m
  chart:
    name: traefik-crds

certManager:
  enabled: true
  targetNamespace: cert-manager
  name: cert-manager
  ocmResourceName: chart
  interval: 1m
  values:
    crds:
      enabled: true

fluxCD:
  kubeConfig:
    # -- If set, all created FluxCD resources will deploy to a remote cluster using this kubeconfig.
    enabled: false
    secretRef:
      # -- name of the secret containing the kubeconfig
      name: platform-mesh-kubeconfig
      key: kubeconfig
