{{- if .Values.gatewayApi.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "common.entity.name" . }}-server
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: {{ .Values.gatewayApi.name }}
    namespace: default
    sectionName: {{ .Values.gatewayApi.main.gateway.name }}
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: {{ include "common.entity.name" . }}-server
      port: {{ .Values.validationServer.port }}
    matches:
    - path:
        type: PathPrefix
        value: {{ .Values.pathPrefix }}
{{- end }}
