apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - contentconfiguration-account-marketplace.yaml
#  - contentconfiguration-account-iam-ui.yaml
#  - contentconfiguration-main-iam-ui.yaml
#  - contentconfiguration-main-marketplace.yaml