resources:
- standard/gateway.networking.k8s.io_gatewayclasses.yaml
- standard/gateway.networking.k8s.io_gateways.yaml
# - standard/gateway.networking.k8s.io_grpcroutes.yaml
- standard/gateway.networking.k8s.io_httproutes.yaml
- standard/gateway.networking.k8s.io_referencegrants.yaml
# - standard/gateway.networking.k8s.io_backendtlspolicies.yaml
# - experimental/gateway.networking.k8s.io_backendtlspolicies.yaml
# - experimental/gateway.networking.k8s.io_gatewayclasses.yaml
# - experimental/gateway.networking.k8s.io_gateways.yaml
- experimental/gateway.networking.k8s.io_grpcroutes.yaml
# - experimental/gateway.networking.k8s.io_httproutes.yaml
# - experimental/gateway.networking.k8s.io_referencegrants.yaml
- experimental/gateway.networking.k8s.io_tcproutes.yaml
- experimental/gateway.networking.k8s.io_tlsroutes.yaml
# - experimental/gateway.networking.x-k8s.io_udproutes.yaml
# - experimental/gateway.networking.x-k8s.io_xbackendtrafficpolicies.yaml
# - experimental/gateway.networking.x-k8s.io_xlistenersets.yaml
# - experimental/gateway.networking.x-k8s.io_xmeshes.yaml