apiVersion: v2
name: example-httpbin-operator
description: A Helm chart for deploying the httpbin operator and its CRDs
type: application
version: 0.5.5
appVersion: "v0.4.5"
annotations:
  # Automatically install and upgrade CRDs
  "helm.sh/resource-policy": keep
