apiVersion: v2
name: example-httpbin-operator
description: A Helm chart for deploying the httpbin operator and its CRDs
type: application
version: 0.5.6
appVersion: "v0.4.7"
annotations:
  # Automatically install and upgrade CRDs
  "helm.sh/resource-policy": keep
