apiVersion: v2
name: organization-idp
description: A Helm chart to deploy organization identity provider in openmfp

type: application
version: 0.5.0
appVersion: "0.0.0"

dependencies:
  - name: common
    version: 0.10.0
    repository: oci://ghcr.io/platform-mesh/helm-charts
