apiVersion: v2
name: organization-idp
description: A Helm chart to deploy organization identity provider in openmfp

type: application
version: 0.5.1
appVersion: "1.0.0"

dependencies:
  - name: common
    version: 0.11.0
    repository: oci://ghcr.io/platform-mesh/helm-charts
