apiVersion: v2
description: Helm Chart for the Platform Mesh Portal
name: portal
version: 0.10.39
appVersion: "v0.17.29"
dependencies:
  - name: common
    repository: oci://ghcr.io/platform-mesh/helm-charts
    version: 0.11.2
