apiVersion: v2
description: Helm Chart for the Platform Mesh Portal
name: portal
version: 0.4.6
appVersion: "v0.16.96"
dependencies:
  - name: common
    repository: oci://ghcr.io/platform-mesh/helm-charts
    version: 0.6.0
