apiVersion: v2
description: Helm Chart for the Platform Mesh Portal
name: portal
version: 0.10.65
appVersion: "v0.18.4"
dependencies:
  - name: common
    repository: oci://ghcr.io/platform-mesh/helm-charts
    version: 0.11.2
