apiVersion: v2
description: Helm Chart for the Platform Mesh Portal
name: portal
version: 0.7.18
appVersion: "v0.16.145"
dependencies:
  - name: common
    repository: oci://ghcr.io/platform-mesh/helm-charts
    version: 0.10.0
