apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - virtualmachine.yaml
  - vpc.yaml
  - subnet.yaml
  - securitygroup.yaml
  - volume.yaml
  - loadbalancer.yaml
