apiVersion: v2
name: rebac-authz-webhook
description: A Helm chart for Kubernetes
type: application
version: 0.11.5
appVersion: "v0.2.84"
dependencies:
  - name: common
    version: 0.9.0
    repository: oci://ghcr.io/platform-mesh/helm-charts
