apiVersion: v2
name: rebac-authz-webhook
description: A Helm chart for Kubernetes
type: application
version: 0.12.24
appVersion: "v0.2.131"
dependencies:
  - name: common
    version: 0.11.0
    repository: oci://ghcr.io/platform-mesh/helm-charts
