apiVersion: v2
name: rebac-authz-webhook
description: A Helm chart for Kubernetes
type: application
version: 0.14.0
appVersion: "v0.2.138"
dependencies:
  - name: common
    version: 0.11.1
    repository: oci://ghcr.io/platform-mesh/helm-charts
