apiVersion: v2
name: rebac-authz-webhook
description: A Helm chart for Kubernetes
type: application
version: 0.14.2
appVersion: "v0.2.139"
dependencies:
  - name: common
    version: 0.11.2
    repository: oci://ghcr.io/platform-mesh/helm-charts
