apiVersion: v2
name: rebac-authz-webhook
description: A Helm chart for Kubernetes
type: application
version: 0.10.35
appVersion: "v0.2.77"
dependencies:
  - name: common
    version: 0.6.0
    repository: oci://ghcr.io/platform-mesh/helm-charts
