apiVersion: v2
version: 0.33.2
appVersion: v0.7.4
name: kubernetes-graphql-gateway
description: Basic helm chart that contains listener and gateway
dependencies:
  - name: common
    version: 0.11.2
    repository: oci://ghcr.io/platform-mesh/helm-charts
  - name: kubernetes-graphql-gateway-crds
    version: 0.0.1
    condition: crds.enabled
    repository: oci://ghcr.io/platform-mesh/helm-charts
