apiVersion: v2
appVersion: "v0.10.1"
description: Helm Chart for the iam-ui
name: iam-ui
version: 0.3.0
dependencies:
  - name: common
    version: 0.10.0
    repository: oci://ghcr.io/platform-mesh/helm-charts
