apiVersion: v2
appVersion: "v0.10.3"
description: Helm Chart for the iam-ui
name: iam-ui
version: 0.5.0
dependencies:
  - name: common
    version: 0.11.0
    repository: oci://ghcr.io/platform-mesh/helm-charts
