apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.entity.name" . }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  {{- include "common.deploymentBasics" . | indent 2 }}
  template:
    metadata:
      labels:
        {{- include "common.labelMatcher" . | indent 8 }}
        control-plane: controller-manager
      annotations:
      {{- if eq (include "common.getKeyValue" (dict "Values" .Values "key" "istio.enabled")) "true" }}
        sidecar.istio.io/inject: "{{ (include "common.istioEnabled" .) }}"
      {{- end -}}
      {{- if ((.Values.deployment).template).annotations }}
      {{ .Values.deployment.template.annotations | toYaml | nindent 8 }}
      {{- end }}
    spec:
      {{ include "common.pod.securityContext" . | nindent 6 }}
      containers:
      - {{- include "common.podBasics" . | indent 8 }}
        {{- include "common.container.securityContext" . | indent 8 }}
        {{- include "common.healthAndReadiness" . | indent 8 }}
        args:
          - operator
          {{- include "common.commonOperatorArgs" . | indent 8 }}
          - --subroutines-deployment-enable-istio={{ (include "common.istioEnabled" .) }}
          {{- if .Values.remotePlatformmesh.enabled }}
          - --remote-platform-mesh-enabled
          - --remote-platform-mesh-kubeconfig=/etc/platformmesh/kubeconfig
          - --remote-platform-mesh-fluxcd-secret-name={{ .Values.remotePlatformmesh.fluxcd.secretName }}
          - --remote-platform-mesh-fluxcd-secret-key={{ .Values.remotePlatformmesh.fluxcd.secretKey }}
          {{- end }}
          {{- if .Values.remoteFluxCD.enabled }}
          - --remote-fluxcd-enabled
          - --remote-fluxcd-kubeconfig=/etc/fluxcd/kubeconfig
          {{- end }}
          {{- include "common.extraArgs" . | nindent 10 }}
        ports:
        {{- include "common.PortsMetricsHealth" . | nindent 10 }}
        env:
        {{- include "common.basicEnvironment" . | nindent 10 }}
        volumeMounts:
        {{- if .Values.remoteFluxCD.enabled }}
        - name: external-fluxcd-deployment
          mountPath: /etc/fluxcd
          readOnly: true
        {{- end }}
        {{- if .Values.remotePlatformmesh.enabled }}
        - name: external-platformmesh-deployment
          mountPath: /etc/platformmesh
          readOnly: true
        {{- end }}
      {{ include "common.hostAliases" $ | nindent 6 }}
      terminationGracePeriodSeconds: {{ include "common.terminationGracePeriodSeconds" .}}
      {{- if .Values.remotePlatformmesh.enabled }}
      volumes:
      {{- if .Values.remoteFluxCD.enabled }}
      - name: external-fluxcd-deployment
        secret:
          secretName: {{ .Values.remoteFluxCD.secretName }}
          secretKey: {{ .Values.remoteFluxCD.secretKey }}
          defaultMode: 420
      {{- end }}
      {{- if .Values.remotePlatformmesh.enabled }}
      - name: external-platformmesh-deployment
        secret:
          secretName: {{ .Values.remotePlatformmesh.operator.secretName }}
          secretKey: {{ .Values.remotePlatformmesh.operator.secretKey }}
          defaultMode: 420
      {{- end }}
      {{- end }}
