apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.entity.name" . }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  {{- include "common.deploymentBasics" . | indent 2 }}
  template:
    metadata:
      labels:
        {{- include "common.labelMatcher" . | indent 8 }}
        control-plane: controller-manager
      annotations:
      {{- if eq (include "common.getKeyValue" (dict "Values" .Values "key" "istio.enabled")) "true" }}
        sidecar.istio.io/inject: "{{ (include "common.istioEnabled" .) }}"
      {{- end -}}
      {{- if ((.Values.deployment).template).annotations }}
      {{ .Values.deployment.template.annotations | toYaml | nindent 8 }}
      {{- end }}
    spec:
      {{ include "common.pod.securityContext" . | nindent 6 }}
      containers:
      - {{- include "common.podBasics" . | indent 8 }}
        {{- include "common.container.securityContext" . | indent 8 }}
        {{- include "common.healthAndReadiness" . | indent 8 }}
        args:
          - operator
          {{- include "common.commonOperatorArgs" . | indent 8 }}
          - --subroutines-deployment-enable-istio={{ (include "common.istioEnabled" .) }}
        ports:
        {{- include "common.PortsMetricsHealth" . | nindent 10 }}
        env:
        {{- include "common.basicEnvironment" . | nindent 10 }}
        {{- if .Values.kubeConfig.enabled }}
        - name: KUBECONFIG
          value: /etc/kubeconfig
        {{- end }}
        {{- if .Values.kubeConfig.enabled }}
        volumeMounts:
        - name: external-kubeconfig
          mountPath: /etc
          readOnly: true
        {{- end }}

      terminationGracePeriodSeconds: {{ include "common.terminationGracePeriodSeconds" .}}
      {{- if .Values.kubeConfig.enabled }}
      volumes:
      - name: external-kubeconfig
        secret:
          secretName: {{ .Values.kubeConfig.secretName }}
          defaultMode: 420
      {{- end }}
