apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.entity.name" . }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  {{- include "common.deploymentBasics" . | indent 2 }}
  template:
    metadata:
      labels:
        {{- include "common.labelMatcher" . | indent 8 }}
        control-plane: controller-manager
      annotations:
      {{- if eq (include "common.getKeyValue" (dict "Values" .Values "key" "istio.enabled")) "true" }}
        sidecar.istio.io/inject: "{{ (include "common.istioEnabled" .) }}"
      {{- end -}}
      {{- if ((.Values.deployment).template).annotations }}
      {{ .Values.deployment.template.annotations | toYaml | nindent 8 }}
      {{- end }}
    spec:
      {{ include "common.pod.securityContext" . | nindent 6 }}
      containers:
      - {{- include "common.podBasics" . | indent 8 }}
        {{- include "common.container.securityContext" . | indent 8 }}
        {{- include "common.healthAndReadiness" . | indent 8 }}
        args:
          - operator
          {{- include "common.commonOperatorArgs" . | indent 8 }}
          - --subroutines-deployment-enable-istio={{ (include "common.istioEnabled" .) }}
          {{- if .Values.remoteRuntime.enabled }}
          - --remote-runtime-enabled=true
          - --remote-runtime-kubeconfig=/etc/platformmesh/kubeconfig
          - --remote-runtime-infra-secret-name={{ .Values.remoteRuntime.infra.secretName }}
          - --remote-runtime-infra-secret-key={{ .Values.remoteRuntime.infra.secretKey }}
          {{- end }}
          {{- if .Values.remoteInfra.enabled }}
          - --remote-infra-enabled
          - --remote-infra-kubeconfig=/etc/infra/kubeconfig
          {{- end }}
          {{- include "common.extraArgs" . | nindent 10 }}
        ports:
        {{- include "common.PortsMetricsHealth" . | nindent 10 }}
        env:
        {{- include "common.basicEnvironment" . | nindent 10 }}
        volumeMounts:
        {{- include "common.extraVolumeMounts" . | nindent 8 }}
        {{- if .Values.remoteInfra.enabled }}
        - name: external-infra-deployment
          mountPath: /etc/infra
          readOnly: true
        {{- end }}
        {{- if .Values.remoteRuntime.enabled }}
        - name: external-platformmesh-deployment
          mountPath: /etc/platformmesh
          readOnly: true
        {{- end }}
      {{ include "common.hostAliases" $ | nindent 6 }}
      terminationGracePeriodSeconds: {{ include "common.terminationGracePeriodSeconds" .}}
      {{- if or .Values.extraVolumes .Values.remoteRuntime.enabled .Values.remoteInfra.enabled }}
      volumes:
      {{- include "common.extraVolumes" . | nindent 6 }}
      {{- if .Values.remoteInfra.enabled }}
      - name: external-infra-deployment
        secret:
          secretName: {{ .Values.remoteInfra.secretName }}
          secretKey: {{ .Values.remoteInfra.secretKey }}
          defaultMode: 420
      {{- end }}
      {{- if .Values.remoteRuntime.enabled }}
      - name: external-platformmesh-deployment
        secret:
          secretName: {{ .Values.remoteRuntime.secretName }}
          secretKey: {{ .Values.remoteRuntime.secretKey }}
          defaultMode: 420
      {{- end }}
      {{- end }}
