apiVersion: v2
appVersion: "v0.1.0"
description: Helm Chart for the generic-resource-ui
name: generic-resource-ui
version: 0.1.0
dependencies:
  - name: common
    version: 0.11.2
    repository: oci://ghcr.io/platform-mesh/helm-charts
