name: Build iam-ui Workflow
on:
  push:
    branches:
      - main
    paths:
      - 'charts/iam-ui/**'
      - '.github/workflows/iam-ui.yaml'
      - '.ocm/component-constructor.yaml'
  pull_request:
    paths:
      - 'charts/iam-ui/**'
      - '.github/workflows/iam-ui.yaml'

permissions:
  contents: read
  packages: write

jobs:
  pipeline:
    concurrency:
      group: iam-ui-${{ github.ref }}
      cancel-in-progress: true
    uses: platform-mesh/.github/.github/workflows/pipeline-chart.yml@main
    with:
      chartFolder: charts
      chartName: iam-ui
      additionalTestFilesCommand: ''
      chartRepos: 'bitnami=https://charts.bitnami.com/bitnami,openfga=https://openfga.github.io/helm-charts'
    secrets: inherit

